<?php

namespace Database\Seeders;

use App\Models\Activity;
use App\Models\Exchange;
use Carbon\Carbon;
use Illuminate\Database\Seeder;

class ActivitiesSeeder extends Seeder
{
    public function run(): void
    {
        /** =========================
         * ITALIA
         * ========================= */
        $italy = Exchange::find(1);
        $startItaly = Carbon::parse($italy->start_date);

        Activity::insert([
            [
                'title' => 'Arribada i instal·lació',
                'description' => 'Arribada a Milà i acomodació a l’allotjament.',
                'type' => 'post',
                'exchange_id' => 1,
                'user_id' => '1',
                'start_date' => $startItaly->copy()->addDays(0)->setTime(8, 0),
                'end_date' => $startItaly->copy()->addDays(0)->setTime(9, 30),
            ],
            [
                'title' => 'Esmorzar italià',
                'description' => 'Primer contacte amb la gastronomia local.',
                'type' => 'post',
                'exchange_id' => 1,
                'user_id' => '1',
                'start_date' => $startItaly->copy()->addDays(0)->setTime(9, 30),
                'end_date' => $startItaly->copy()->addDays(0)->setTime(10, 30),
            ],
            [
                'title' => 'Gimcana de Devs',
                'description' => 'Preguntes per la demo de classe.',
                'type' => 'gimcana',
                'exchange_id' => 1,
                'user_id' => '1',
                'start_date' => $startItaly->copy()->addDays(0)->setTime(9, 30),
                'end_date' => $startItaly->copy()->addDays(0)->setTime(10, 30),
            ],
            [
                'title' => 'Visita al Duomo de Milà',
                'description' => 'Descobreix la catedral més emblemàtica de Milà.',
                'type' => 'post',
                'exchange_id' => 1,
                'user_id' => '1',
                'start_date' => $startItaly->copy()->addDays(0)->setTime(11, 0),
                'end_date' => $startItaly->copy()->addDays(0)->setTime(13, 0),
            ],
            [
                'title' => 'Galeria Vittorio Emanuele II',
                'description' => 'Passeig per una galeria històrica i comercial.',
                'type' => 'post',
                'exchange_id' => 1,
                'user_id' => '2',
                'start_date' => $startItaly->copy()->addDays(1)->setTime(10, 0),
                'end_date' => $startItaly->copy()->addDays(1)->setTime(12, 0),
            ],
            [
                'title' => 'Museu del Novecento',
                'description' => 'Art modern italià amb vistes al Duomo.',
                'type' => 'post',
                'exchange_id' => 1,
                'user_id' => '3',
                'start_date' => $startItaly->copy()->addDays(1)->setTime(14, 0),
                'end_date' => $startItaly->copy()->addDays(1)->setTime(16, 0),
            ],
            [
                'title' => 'Brera i Pinacoteca',
                'description' => 'Barri bohemi i galeria d’art clàssic.',
                'type' => 'interest_point',
                'exchange_id' => 1,
                'user_id' => '1',
                'start_date' => $startItaly->copy()->addDays(1)->setTime(17, 0),
                'end_date' => $startItaly->copy()->addDays(1)->setTime(19, 0),
            ],
            [
                'title' => 'Parc Sempione',
                'description' => 'Relax al parc més gran de Milà.',
                'type' => 'guided_visit',
                'exchange_id' => 1,
                'user_id' => '2',
                'start_date' => $startItaly->copy()->addDays(2)->setTime(10, 0),
                'end_date' => $startItaly->copy()->addDays(2)->setTime(12, 0),
            ],
            [
                'title' => 'Castell Sforzesco',
                'description' => 'Explora aquest castell i els seus museus.',
                'type' => 'gimcana',
                'exchange_id' => 1,
                'user_id' => '1',
                'start_date' => $startItaly->copy()->addDays(2)->setTime(16, 0),
                'end_date' => $startItaly->copy()->addDays(2)->setTime(18, 0),
            ],
            [
                'title' => 'Visita a l’Universitat de Milà',
                'description' => 'Intercanvi cultural amb estudiants locals.',
                'type' => 'post',
                'exchange_id' => 1,
                'user_id' => '2',
                'start_date' => $startItaly->copy()->addDays(3)->setTime(10, 0),
                'end_date' => $startItaly->copy()->addDays(3)->setTime(13, 0),
            ],
            [
                'title' => 'Temps lliure',
                'description' => 'Exploració lliure de la ciutat.',
                'type' => 'post',
                'exchange_id' => 1,
                'user_id' => '3',
                'start_date' => $startItaly->copy()->addDays(3)->setTime(16, 0),
                'end_date' => $startItaly->copy()->addDays(3)->setTime(18, 0),
            ],
            [
                'title' => 'Sopar de grup',
                'description' => 'Sopar conjunt per compartir l’experiència.',
                'type' => 'post',
                'exchange_id' => 1,
                'user_id' => '1',
                'start_date' => $startItaly->copy()->addDays(3)->setTime(20, 0),
                'end_date' => $startItaly->copy()->addDays(3)->setTime(22, 0),
            ],
            [
                'title' => 'Cenacolo Vinciano',
                'description' => 'Veure "L’Últim Sopar" de Leonardo da Vinci.',
                'type' => 'post',
                'exchange_id' => 1,
                'user_id' => '1',
                'start_date' => $startItaly->copy()->addDays(4)->setTime(10, 0),
                'end_date' => $startItaly->copy()->addDays(4)->setTime(12, 0),
            ],
            [
                'title' => 'Shopping a Corso Buenos Aires',
                'description' => 'Una de les principals avingudes comercials de Milà.',
                'type' => 'post',
                'exchange_id' => 1,
                'user_id' => '1',
                'start_date' => $startItaly->copy()->addDays(5)->setTime(10, 0),
                'end_date' => $startItaly->copy()->addDays(5)->setTime(12, 0),
            ],
            [
                'title' => 'Tornada a casa',
                'description' => 'Sortida cap a Figueres.',
                'type' => 'post',
                'exchange_id' => 1,
                'user_id' => '1',
                'start_date' => $startItaly->copy()->addDays(5)->setTime(14, 0),
                'end_date' => $startItaly->copy()->addDays(5)->setTime(18, 0),
            ],
            [
                'title' => 'Taller de cuina italiana',
                'description' => 'Classe practica per aprendre plats tradicionals.',
                'type' => 'post',
                'exchange_id' => 1,
                'user_id' => '2',
                'start_date' => $startItaly->copy()->addDays(2)->setTime(13, 30),
                'end_date' => $startItaly->copy()->addDays(2)->setTime(15, 0),
            ],
            [
                'title' => 'Excursio al llac de Como',
                'description' => 'Sortida dfda per cone8ixer el llac.',
                'type' => 'post',
                'exchange_id' => 1,
                'user_id' => '3',
                'start_date' => $startItaly->copy()->addDays(4)->setTime(8, 30),
                'end_date' => $startItaly->copy()->addDays(4)->setTime(16, 0),
            ],
            [
                'title' => 'Santa Maria delle Grazie',
                'description' => 'Basedlica renaixentista al centre de Mile0.',
                'type' => 'interest_point',
                'exchange_id' => 1,
                'user_id' => '1',
                'start_date' => $startItaly->copy()->addDays(2)->setTime(11, 0),
                'end_date' => $startItaly->copy()->addDays(2)->setTime(12, 0),
            ],
            [
                'title' => 'Canals dels Navigli',
                'description' => 'Zona de canals amb ambient cultural i gastronomic.',
                'type' => 'interest_point',
                'exchange_id' => 1,
                'user_id' => '2',
                'start_date' => $startItaly->copy()->addDays(4)->setTime(18, 30),
                'end_date' => $startItaly->copy()->addDays(4)->setTime(20, 0),
            ],
            [
                'title' => 'Teatre alla Scala (visita guiada)',
                'description' => 'Visita guiada al teatre mes emblematic.',
                'type' => 'guided_visit',
                'exchange_id' => 1,
                'user_id' => '1',
                'start_date' => $startItaly->copy()->addDays(1)->setTime(15, 30),
                'end_date' => $startItaly->copy()->addDays(1)->setTime(17, 0),
            ],
            [
                'title' => 'Navigli al capvespre (visita guiada)',
                'description' => 'Ruta guiada pels canals al vespre.',
                'type' => 'guided_visit',
                'exchange_id' => 1,
                'user_id' => '3',
                'start_date' => $startItaly->copy()->addDays(2)->setTime(19, 0),
                'end_date' => $startItaly->copy()->addDays(2)->setTime(21, 0),
            ],
            [
                'title' => 'Gimcana del centre historic de Mila',
                'description' => 'Proves culturals pels carrers centrals.',
                'type' => 'gimcana',
                'exchange_id' => 1,
                'user_id' => '2',
                'start_date' => $startItaly->copy()->addDays(1)->setTime(9, 0),
                'end_date' => $startItaly->copy()->addDays(1)->setTime(11, 0),
            ],
            [
                'title' => 'Gimcana del barri de Brera',
                'description' => 'Ruta en equips pel barri artistic.',
                'type' => 'gimcana',
                'exchange_id' => 1,
                'user_id' => '1',
                'start_date' => $startItaly->copy()->addDays(3)->setTime(12, 30),
                'end_date' => $startItaly->copy()->addDays(3)->setTime(14, 0),
            ],
        ]);

        /** =========================
         * ALEMANIA
         * ========================= */
        $germany = Exchange::find(2);
        $startGermany = Carbon::parse($germany->start_date);

        Activity::insert([
            [
                'title' => 'Mur de Berlín',
                'description' => 'Història i recorregut pel mur.',
                'type' => 'post',
                'exchange_id' => 2,
                'user_id' => '1',
                'start_date' => $startGermany->copy()->addDays(1)->setTime(10, 0),
                'end_date' => $startGermany->copy()->addDays(1)->setTime(12, 0),
            ],
            [
                'title' => 'Reichstag',
                'description' => 'Visita al parlament alemany.',
                'type' => 'post',
                'exchange_id' => 2,
                'user_id' => '1',
                'start_date' => $startGermany->copy()->addDays(3)->setTime(11, 0),
                'end_date' => $startGermany->copy()->addDays(3)->setTime(13, 0),
            ],
            [
                'title' => 'Porta de Brandenburg',
                'description' => 'Símbol icònic de Berlín.',
                'type' => 'post',
                'exchange_id' => 2,
                'user_id' => '1',
                'start_date' => $startGermany->copy()->addDays(5)->setTime(16, 0),
                'end_date' => $startGermany->copy()->addDays(5)->setTime(18, 0),
            ],
        ]);

        /** =========================
         * FRANCIA
         * ========================= */
        $france = Exchange::find(3);
        $startFrance = Carbon::parse($france->start_date);

        Activity::insert([
            [
                'title' => 'Passeig per Kreuzberg',
                'description' => 'Ruta lliure per un barri multicultural.',
                'type' => 'post',
                'exchange_id' => 2,
                'user_id' => '2',
                'start_date' => $startGermany->copy()->addDays(2)->setTime(15, 0),
                'end_date' => $startGermany->copy()->addDays(2)->setTime(17, 0),
            ],
            [
                'title' => 'Sopar alemany',
                'description' => 'Tast de plats tradicionals de Berledn.',
                'type' => 'post',
                'exchange_id' => 2,
                'user_id' => '3',
                'start_date' => $startGermany->copy()->addDays(4)->setTime(19, 0),
                'end_date' => $startGermany->copy()->addDays(4)->setTime(21, 0),
            ],
            [
                'title' => 'Illa dels Museus',
                'description' => 'Conjunt de museus a ledlla del riu Spree.',
                'type' => 'interest_point',
                'exchange_id' => 2,
                'user_id' => '1',
                'start_date' => $startGermany->copy()->addDays(1)->setTime(14, 0),
                'end_date' => $startGermany->copy()->addDays(1)->setTime(16, 0),
            ],
            [
                'title' => 'Alexanderplatz',
                'description' => 'Plae7a central amb vistes urbanes.',
                'type' => 'interest_point',
                'exchange_id' => 2,
                'user_id' => '2',
                'start_date' => $startGermany->copy()->addDays(3)->setTime(10, 0),
                'end_date' => $startGermany->copy()->addDays(3)->setTime(11, 0),
            ],
            [
                'title' => 'Memorial de l\'Holocaust (visita guiada)',
                'description' => 'Visita guiada al memorial central.',
                'type' => 'guided_visit',
                'exchange_id' => 2,
                'user_id' => '1',
                'start_date' => $startGermany->copy()->addDays(2)->setTime(10, 0),
                'end_date' => $startGermany->copy()->addDays(2)->setTime(12, 0),
            ],
            [
                'title' => 'Potsdamer Platz (visita guiada)',
                'description' => 'Recorregut guiada per l\'arquitectura moderna.',
                'type' => 'guided_visit',
                'exchange_id' => 2,
                'user_id' => '3',
                'start_date' => $startGermany->copy()->addDays(4)->setTime(10, 30),
                'end_date' => $startGermany->copy()->addDays(4)->setTime(12, 0),
            ],
            [
                'title' => 'Gimcana historica de Mitte',
                'description' => 'Proves culturals al cor de Berledn.',
                'type' => 'gimcana',
                'exchange_id' => 2,
                'user_id' => '2',
                'start_date' => $startGermany->copy()->addDays(1)->setTime(9, 0),
                'end_date' => $startGermany->copy()->addDays(1)->setTime(10, 30),
            ],
            [
                'title' => 'Gimcana del riu Spree',
                'description' => 'Ruta per punts clau del riu.',
                'type' => 'gimcana',
                'exchange_id' => 2,
                'user_id' => '1',
                'start_date' => $startGermany->copy()->addDays(5)->setTime(9, 30),
                'end_date' => $startGermany->copy()->addDays(5)->setTime(11, 0),
            ],
            [
                'title' => 'Torre Eiffel',
                'description' => 'Visita guiada al monument més famós.',
                'type' => 'post',
                'exchange_id' => 3,
                'user_id' => '1',
                'start_date' => $startFrance->copy()->addDays(0)->setTime(10, 0),
                'end_date' => $startFrance->copy()->addDays(0)->setTime(12, 0),
            ],
            [
                'title' => 'Passeig pel Sena',
                'description' => 'Ruta en vaixell per París.',
                'type' => 'post',
                'exchange_id' => 3,
                'user_id' => '1',
                'start_date' => $startFrance->copy()->addDays(1)->setTime(11, 0),
                'end_date' => $startFrance->copy()->addDays(1)->setTime(13, 0),
            ],
            [
                'title' => 'Museu del Louvre',
                'description' => 'Exploració artística guiada.',
                'type' => 'post',
                'exchange_id' => 3,
                'user_id' => '1',
                'start_date' => $startFrance->copy()->addDays(2)->setTime(10, 0),
                'end_date' => $startFrance->copy()->addDays(2)->setTime(13, 0),
            ],
            [
                'title' => 'Montmartre',
                'description' => 'Barri bohemi i cultural.',
                'type' => 'post',
                'exchange_id' => 3,
                'user_id' => '1',
                'start_date' => $startFrance->copy()->addDays(3)->setTime(16, 0),
                'end_date' => $startFrance->copy()->addDays(3)->setTime(18, 0),
            ],
            [
                'title' => 'Versalles',
                'description' => 'Excursió al palau.',
                'type' => 'post',
                'exchange_id' => 3,
                'user_id' => '1',
                'start_date' => $startFrance->copy()->addDays(4)->setTime(9, 0),
                'end_date' => $startFrance->copy()->addDays(4)->setTime(14, 0),
            ],
            [
                'title' => 'Mercat local de Paris',
                'description' => 'Tast de productes i ambient parisenc.',
                'type' => 'post',
                'exchange_id' => 3,
                'user_id' => '2',
                'start_date' => $startFrance->copy()->addDays(0)->setTime(15, 0),
                'end_date' => $startFrance->copy()->addDays(0)->setTime(16, 0),
            ],
            [
                'title' => 'Taller de creps',
                'description' => 'Activitat culinaria per aprendre receptes.',
                'type' => 'post',
                'exchange_id' => 3,
                'user_id' => '3',
                'start_date' => $startFrance->copy()->addDays(2)->setTime(17, 0),
                'end_date' => $startFrance->copy()->addDays(2)->setTime(18, 30),
            ],
            [
                'title' => 'Jardins de Luxemburg',
                'description' => 'Espai verd i cultural al centre de Paris.',
                'type' => 'interest_point',
                'exchange_id' => 3,
                'user_id' => '1',
                'start_date' => $startFrance->copy()->addDays(1)->setTime(15, 30),
                'end_date' => $startFrance->copy()->addDays(1)->setTime(17, 0),
            ],
            [
                'title' => 'Catedral de Notre-Dame (exterior)',
                'description' => 'Visita a l\'entorn de la catedral.',
                'type' => 'interest_point',
                'exchange_id' => 3,
                'user_id' => '2',
                'start_date' => $startFrance->copy()->addDays(3)->setTime(10, 0),
                'end_date' => $startFrance->copy()->addDays(3)->setTime(11, 0),
            ],
            [
                'title' => 'Museu d\'Orsay (visita guiada)',
                'description' => 'Ruta guiada per l\'art impressionista.',
                'type' => 'guided_visit',
                'exchange_id' => 3,
                'user_id' => '1',
                'start_date' => $startFrance->copy()->addDays(1)->setTime(9, 30),
                'end_date' => $startFrance->copy()->addDays(1)->setTime(11, 0),
            ],
            [
                'title' => 'Barri Llati (visita guiada)',
                'description' => 'Passeig guiat pel barri universitari.',
                'type' => 'guided_visit',
                'exchange_id' => 3,
                'user_id' => '3',
                'start_date' => $startFrance->copy()->addDays(4)->setTime(15, 0),
                'end_date' => $startFrance->copy()->addDays(4)->setTime(17, 0),
            ],
            [
                'title' => 'Gimcana del Marais',
                'description' => 'Proves culturals pel barri historic.',
                'type' => 'gimcana',
                'exchange_id' => 3,
                'user_id' => '2',
                'start_date' => $startFrance->copy()->addDays(2)->setTime(9, 30),
                'end_date' => $startFrance->copy()->addDays(2)->setTime(11, 0),
            ],
            [
                'title' => 'Gimcana per l\'Ile de la Cite',
                'description' => 'Ruta en equip per l\'illa central.',
                'type' => 'gimcana',
                'exchange_id' => 3,
                'user_id' => '1',
                'start_date' => $startFrance->copy()->addDays(3)->setTime(13, 0),
                'end_date' => $startFrance->copy()->addDays(3)->setTime(14, 30),
            ],
        ]);

        /** =========================
         * PORTUGAL
         * ========================= */
        $portugal = Exchange::find(4);
        $startPortugal = Carbon::parse($portugal->start_date);

        Activity::insert([
            [
                'title' => 'Arribada a Lisboa',
                'description' => 'Recepcio i acomodacio al centre.',
                'type' => 'post',
                'exchange_id' => 4,
                'user_id' => '1',
                'start_date' => $startPortugal->copy()->addDays(0)->setTime(9, 30),
                'end_date' => $startPortugal->copy()->addDays(0)->setTime(11, 0),
            ],
            [
                'title' => 'Passeig per Belem',
                'description' => 'Ruta pel barri maritim i els seus monuments.',
                'type' => 'post',
                'exchange_id' => 4,
                'user_id' => '2',
                'start_date' => $startPortugal->copy()->addDays(1)->setTime(16, 0),
                'end_date' => $startPortugal->copy()->addDays(1)->setTime(18, 0),
            ],
            [
                'title' => 'Torre de Belem',
                'description' => 'Punt historica a la riba del Tajo.',
                'type' => 'interest_point',
                'exchange_id' => 4,
                'user_id' => '1',
                'start_date' => $startPortugal->copy()->addDays(2)->setTime(10, 0),
                'end_date' => $startPortugal->copy()->addDays(2)->setTime(11, 0),
            ],
            [
                'title' => 'Barri d\'Alfama',
                'description' => 'Carrers estrets i miradors amb vistes.',
                'type' => 'interest_point',
                'exchange_id' => 4,
                'user_id' => '3',
                'start_date' => $startPortugal->copy()->addDays(3)->setTime(10, 30),
                'end_date' => $startPortugal->copy()->addDays(3)->setTime(12, 0),
            ],
            [
                'title' => 'Monestir dels Jeronims (visita guiada)',
                'description' => 'Ruta guiada pel monestir manueli.',
                'type' => 'guided_visit',
                'exchange_id' => 4,
                'user_id' => '2',
                'start_date' => $startPortugal->copy()->addDays(2)->setTime(12, 30),
                'end_date' => $startPortugal->copy()->addDays(2)->setTime(14, 0),
            ],
            [
                'title' => 'Oceanari de Lisboa (visita guiada)',
                'description' => 'Visita guiada a l\'oceanari.',
                'type' => 'guided_visit',
                'exchange_id' => 4,
                'user_id' => '1',
                'start_date' => $startPortugal->copy()->addDays(4)->setTime(11, 0),
                'end_date' => $startPortugal->copy()->addDays(4)->setTime(13, 0),
            ],
            [
                'title' => 'Gimcana del barri de Baixa',
                'description' => 'Proves i enigmes al centre comercial.',
                'type' => 'gimcana',
                'exchange_id' => 4,
                'user_id' => '3',
                'start_date' => $startPortugal->copy()->addDays(3)->setTime(15, 0),
                'end_date' => $startPortugal->copy()->addDays(3)->setTime(16, 30),
            ],
            [
                'title' => 'Gimcana de miradors',
                'description' => 'Ruta pels principals miradors de Lisboa.',
                'type' => 'gimcana',
                'exchange_id' => 4,
                'user_id' => '2',
                'start_date' => $startPortugal->copy()->addDays(5)->setTime(9, 30),
                'end_date' => $startPortugal->copy()->addDays(5)->setTime(11, 0),
            ],
        ]);

        /** =========================
         * IRLANDA
         * ========================= */
        $ireland = Exchange::find(5);
        $startIreland = Carbon::parse($ireland->start_date);

        Activity::insert([
            [
                'title' => 'Arribada a Dublin',
                'description' => 'Benvinguda i distribucio dels grups.',
                'type' => 'post',
                'exchange_id' => 5,
                'user_id' => '1',
                'start_date' => $startIreland->copy()->addDays(0)->setTime(10, 0),
                'end_date' => $startIreland->copy()->addDays(0)->setTime(11, 30),
            ],
            [
                'title' => 'Trinity College Library',
                'description' => 'Visita a la biblioteca i el Book of Kells.',
                'type' => 'post',
                'exchange_id' => 5,
                'user_id' => '2',
                'start_date' => $startIreland->copy()->addDays(1)->setTime(12, 0),
                'end_date' => $startIreland->copy()->addDays(1)->setTime(13, 30),
            ],
            [
                'title' => 'Temple Bar',
                'description' => 'Barri historic amb ambient cultural.',
                'type' => 'interest_point',
                'exchange_id' => 5,
                'user_id' => '3',
                'start_date' => $startIreland->copy()->addDays(2)->setTime(16, 0),
                'end_date' => $startIreland->copy()->addDays(2)->setTime(17, 0),
            ],
            [
                'title' => 'Phoenix Park',
                'description' => 'Parc urba amb fauna i monuments.',
                'type' => 'interest_point',
                'exchange_id' => 5,
                'user_id' => '1',
                'start_date' => $startIreland->copy()->addDays(3)->setTime(10, 0),
                'end_date' => $startIreland->copy()->addDays(3)->setTime(12, 0),
            ],
            [
                'title' => 'Guinness Storehouse (visita guiada)',
                'description' => 'Recorregut guiat per la fabrica historica.',
                'type' => 'guided_visit',
                'exchange_id' => 5,
                'user_id' => '2',
                'start_date' => $startIreland->copy()->addDays(2)->setTime(10, 0),
                'end_date' => $startIreland->copy()->addDays(2)->setTime(12, 0),
            ],
            [
                'title' => 'Kilmainham Gaol (visita guiada)',
                'description' => 'Visita guiada a l\'antic presidi.',
                'type' => 'guided_visit',
                'exchange_id' => 5,
                'user_id' => '3',
                'start_date' => $startIreland->copy()->addDays(4)->setTime(11, 0),
                'end_date' => $startIreland->copy()->addDays(4)->setTime(12, 30),
            ],
            [
                'title' => 'Gimcana del centre de Dublin',
                'description' => 'Proves culturals al centre de la ciutat.',
                'type' => 'gimcana',
                'exchange_id' => 5,
                'user_id' => '1',
                'start_date' => $startIreland->copy()->addDays(1)->setTime(9, 30),
                'end_date' => $startIreland->copy()->addDays(1)->setTime(11, 0),
            ],
            [
                'title' => 'Gimcana del riu Liffey',
                'description' => 'Ruta en equips pels ponts principals.',
                'type' => 'gimcana',
                'exchange_id' => 5,
                'user_id' => '2',
                'start_date' => $startIreland->copy()->addDays(5)->setTime(10, 0),
                'end_date' => $startIreland->copy()->addDays(5)->setTime(11, 30),
            ],
        ]);
    }
}
